---
- name: Install and start apache
  hosts: webservers
  become: yes

  tasks:
  - name: Install Apache
    yum:
      name: httpd
      state: present

  - name: Start service httpd, if not running
    service:
      name: httpd
      state: started

