---
- name: Set Up Flask App Server
  hosts: "localhost" 
  become: yes

  environment:
    ANSIBLE_HOST_KEY_CHECKING: "False"

  tasks:
    - name: Update package cache
      apt:
        update_cache: yes
      when: ansible_distribution == 'Ubuntu'

    - name: Install Python 3 and pip
      apt:
        name:
          - python3
          - python3-pip
        state: present
      when: ansible_distribution == 'Ubuntu'

    - name: Clone Git repository
      git:
        repo: https://github.com/MuhammadSalah99/dockerize-flaskapp-through-bash.git
        dest: /opt/app
      tags:
        - git

    - name: Install app dependencies
      pip3:
        requirements: /opt/app/requirements.txt

    - name: Run Flask app
      command: python3  /opt/app/app.py

