---
- name: Install and Configure PostgreSQL
  hosts: "{{ target_hosts }}"
  become: yes
  gather_facts: no

  tasks:

    - name: Install Python 3
      command: yum install -y python3
      args:
        executable: /bin/bash

    - name: Install pip for Python 3
      command: curl https://bootstrap.pypa.io/get-pip.py | python3
      args:
        executable: /bin/bash
 
    - name: Install psycopg2 Python library
      pip:
        name: python3-psycopg2  
        state: present

    - name: Install PostgreSQL
      pip:
        name: postgresql
        state: present

    - name: Create PostgreSQL User
      postgresql_user:
        db: db
        user: admin
        password: admin
        priv: ALL
        state: present
        login_host: localhost
        login_user: postgres
   
